-- phpMyAdmin SQL Dump
-- version 4.1.14
-- http://www.phpmyadmin.net
--
-- Host: 127.0.0.1
-- Generation Time: 2014-08-22 05:34:14
-- 服务器版本： 5.6.17
-- PHP Version: 5.5.12

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;

--
-- Database: `lab_baozha`
--

-- --------------------------------------------------------

--
-- 表的结构 `np_group_en`
--

CREATE TABLE IF NOT EXISTS `np_group_en` (
  `gid` int(11) NOT NULL AUTO_INCREMENT,
  `title` varchar(50) NOT NULL,
  
  `content` text NOT NULL,
  `order` int(11) NOT NULL,
  PRIMARY KEY (`gid`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 AUTO_INCREMENT=29 ;

--
-- 转存表中的数据 `np_group_en`
--

INSERT INTO `np_group_en` (`gid`, `title`, `content`, `order`) VALUES
(24, 'Wang-FuChi', '', '<p><span style="font-size: 18px;"><span style="text-indent: 25px; background-color: rgb(255, 255, 255); line-height: 30px; font-family: &#39;Times New Roman&#39;;">Doctor, Prof, PhD supervisors. He is an expert and general secretary of advanced material special group General Armament Department, a member of Advanced Material Expert Argue-Group of National Security Important Basic Science Research Project. He won 3 awards of ministerial level and 1 first prize of&nbsp;</span><span style="text-indent: 25px; background-color: rgb(255, 255, 255); line-height: 30px; font-family: &#39;Times New Roman&#39;;">Defense Technical Invention Award</span><span style="text-indent: 25px; background-color: rgb(255, 255, 255); line-height: 30px; font-family: &#39;Times New Roman&#39;;">, and 6 authorized patents.</span></span></p>', 12),
(25, 'Zhang-QingMing', '', '<p><span style="font-size: 18px;"><span style="text-indent: 25px; background-color: rgb(255, 255, 255); line-height: 30px; font-family: &#39;Times New Roman&#39;;">Doctor, Prof</span><span style="font-family: 宋体; text-indent: 25px; background-color: rgb(255, 255, 255); line-height: 30px;">，</span><span style="text-indent: 25px; background-color: rgb(255, 255, 255); line-height: 30px; font-family: &#39;Times New Roman&#39;;">PhD supervisors</span><span style="font-family: 宋体; text-indent: 25px; background-color: rgb(255, 255, 255); line-height: 30px;">，</span><span style="text-indent: 25px; background-color: rgb(255, 255, 255); line-height: 30px; font-family: &#39;Times New Roman&#39;;">Director of&nbsp;<a name="OLE_LINK21"></a>SKLEST. He assumes vice chief editor of Journal of Explosion and Shock Waves, standing editor of Journal of Acta Ordnance, member of explosion Mechanics professional committee of China Mechanics Association, syndic of China Aerodynamics Association. He has been engaged in research on impact dynamics. His research direction is hypervelocity impact mechanism. He has published 2 monographs, 2 translations of works, 10 SCI and 26 EI papers and won&nbsp;1 a&nbsp;first prize, a second prize and a third prize award of ministerial-level, 1 authorized patent and 5 declared patents.</span></span></p>', 13),
(23, 'Ning-JianGuo', '', '<p><span style="color: rgb(51, 51, 51); font-family: &#39;times new roman&#39;; font-size: 18px; line-height: 24px; background-color: rgb(255, 255, 255);">Doctor, Prof, PhD supervisors. He is a vice-director of Applied Mechanics Professional Committee of China Ordnance Society, member of Calculating Mechanics Professional Committee, Logos-Mechanics and Mathematics Method in Mechanics Professional committee of China Mechanics Society, a leader of Calculating Explosion Mechanics Professional Team of Explosion Mechanics Special Committee, China Mechanics Academy, vice leader of Plastic Mechanics Professional Team of Solid Mechanics Professional Committee, China Mechanics Society. He is an editor of Journal of Computational Mechanics, Explosion and Shock Waves. He published more than 100 papers in which 70 indexed by SCI and EI. He has obtained a first-class and a second-class award of ministerial-level for Progress in Science and Technology, several authorized national defense patents and software copyrights.</span></p>', 11),
(22, 'Hu-GengKai', '', '<p><span style="color: rgb(51, 51, 51); font-family: &#39;times new roman&#39;; font-size: 18px; line-height: 24px; background-color: rgb(255, 255, 255);">Doctor, Prof, PhD supervisors. &nbsp;He is a standing syndic of China Mechanics Society, a syndic of China Ordnance Society, director member of Applied Mechanics Professional Committee of China Ordnance Society, member of Solid Mechanics Professional Committee of China Mechanics Society. He is a standing editor of Advances in Mechanics, editors of International Journal of Acta Mechanica , Acta　Mechanica　Sinica and Acta Mechnica Solid Sinica, &nbsp;Applied Mechanics and Mathematics and Mechanics in Engineering. He has published 83 papers in which 43 published in international famous journal.</span></p>', 10),
(19, 'Li-QianShu', '', '<p><span style="font-size: 18px;"><span style="font-family: &#39;Times New Roman&#39;; line-height: 24px; background-color: rgb(255, 255, 255);">Prof</span><span style="line-height: 24px; background-color: rgb(255, 255, 255); font-family: 宋体;">，</span><span style="font-family: &#39;Times New Roman&#39;; line-height: 24px; background-color: rgb(255, 255, 255);">PhD supervisors, Doctor got in JiLin University at 1987. He successively assumes the eighth editor member of China Science, vice-chief editor of Journal of Molecule Science of Chinese Chemistry Association, Chinese vice-representative of World Theoretical Organic Chemists Association. He has written 6 monographs collaborated with others and published SCI paper more than 300, a second prize in State Natural Science Award and 3 ministerial-level awards.</span></span></p>', 7),
(20, 'Jiao Qingjie', '', '<p>&nbsp;</p>', 8),
(21, 'Bai-ChunHua', '', '<p><span style="font-size: 18px;"><span style="line-height: 24px; background-color: rgb(255, 255, 255); font-family: &#39;Times New Roman&#39;;">Doctor</span><span style="font-family: 宋体; line-height: 24px; background-color: rgb(255, 255, 255);">，</span><span style="line-height: 24px; background-color: rgb(255, 255, 255); font-family: &#39;Times New Roman&#39;;">Prof</span><span style="font-family: 宋体; line-height: 24px; background-color: rgb(255, 255, 255);">，</span><span style="line-height: 24px; background-color: rgb(255, 255, 255); font-family: &#39;Times New Roman&#39;;">PhD supervisors.&nbsp;He is a leader of Division 5.&nbsp;He assumes an expert in National Security product, Editorial Board&nbsp;<a name="OLE_LINK23"></a>of Science &amp; Technology Review,&nbsp;<a name="OLE_LINK24"></a>Journal of China Safety Science, Journal of Explosive and Propellants. He has published more than 150 papers and 3 monographs, 12 patents and won 4 province-ministry class awards.</span></span></p>', 9),
(13, 'Zhang-TongLai', '', '<p><span style="font-size: 18px; font-family: &#39;Times New Roman&#39;; line-height: 24px; background-color: rgb(255, 255, 255);">Doctor, Professor, PhD supervisors. He is a member of Thermal Analyze Professional Committee, China Chemistry Society, Technology and Industry for National Defense Civilian-Explosion Equipment Expert Committee, Initiating Explosive Device of Civilian-Explosion Equipment Expert Team, Technology and Industry for National Defense Civilian-Explosion Equipment Industry Standardization Committee and an editor of Energetic Materials. He has obtained 1 first-class, 1 second-class prize&nbsp;for Progress in&nbsp;National Defense&nbsp;Science and Technology. He won 20 authorized patents and published more than 250 papers in which 100 indexed by abstracting indexes SCI, EI and ISTP.&nbsp;</span></p>', 1),
(14, 'Hu-GengKai', '', '<p><span style="color: rgb(51, 51, 51); font-family: &#39;times new roman&#39;; font-size: 18px; line-height: 24px; background-color: rgb(255, 255, 255);">Doctor, Prof, PhD supervisors. &nbsp;He is a standing syndic of China Mechanics Society, a syndic of China Ordnance Society, director member of Applied Mechanics Professional Committee of China Ordnance Society, member of Solid Mechanics Professional Committee of China Mechanics Society. He is a standing editor of Advances in Mechanics, editors of International Journal of Acta Mechanica , Acta　Mechanica　Sinica and Acta Mechnica Solid Sinica, &nbsp;Applied Mechanics and Mathematics and Mechanics in Engineering. He has published 83 papers in which 43 published in international famous journal.</span></p>', 2),
(15, 'Ning-JianGuo', '', '<p><span style="color: rgb(51, 51, 51); font-family: &#39;times new roman&#39;; font-size: 18px; line-height: 24px; background-color: rgb(255, 255, 255);">Doctor, Prof, PhD supervisors. He is a vice-director of Applied Mechanics Professional Committee of China Ordnance Society, member of Calculating Mechanics Professional Committee, Logos-Mechanics and Mathematics Method in Mechanics Professional committee of China Mechanics Society, a leader of Calculating Explosion Mechanics Professional Team of Explosion Mechanics Special Committee, China Mechanics Academy, vice leader of Plastic Mechanics Professional Team of Solid Mechanics Professional Committee, China Mechanics Society. He is an editor of Journal of Computational Mechanics, Explosion and Shock Waves. He published more than 100 papers in which 70 indexed by SCI and EI. He has obtained a first-class and a second-class award of ministerial-level for Progress in Science and Technology, several authorized national defense patents and software copyrights.</span></p><p><span style="color: rgb(51, 51, 51); font-family: 宋体; font-size: 20px; line-height: 24px; background-color: rgb(255, 255, 255);"></span></p>', 3),
(16, 'Wang-FuChi', '', '<p><span style="font-size: 18px; text-indent: 25px; background-color: rgb(255, 255, 255); line-height: 30px; font-family: &#39;Times New Roman&#39;;"></span><span style="font-size: 18px;"><span style="text-indent: 25px; background-color: rgb(255, 255, 255); line-height: 30px; font-family: &#39;Times New Roman&#39;;">Doctor, Prof, PhD supervisors. He is an expert and general secretary of advanced material special group General Armament Department, a member of Advanced Material Expert Argue-Group of National Security Important Basic Science Research Project. He won 3 awards of ministerial level and 1 first prize of&nbsp;</span><span style="text-indent: 25px; background-color: rgb(255, 255, 255); color: windowtext; line-height: 30px; font-family: &#39;Times New Roman&#39;;">Defense Technical Invention Award</span><span style="text-indent: 25px; background-color: rgb(255, 255, 255); line-height: 30px; font-family: &#39;Times New Roman&#39;;">, and 6 authorized patents.</span></span></p>', 4),
(17, 'Zhang-QingMing', '', '<p><span style="font-size: 18px;"><span style="text-indent: 25px; background-color: rgb(255, 255, 255); line-height: 30px; font-family: &#39;Times New Roman&#39;;">Doctor, Prof</span><span style="font-family: 宋体; text-indent: 25px; background-color: rgb(255, 255, 255); line-height: 30px;">，</span><span style="text-indent: 25px; background-color: rgb(255, 255, 255); line-height: 30px; font-family: &#39;Times New Roman&#39;;">PhD supervisors</span><span style="font-family: 宋体; text-indent: 25px; background-color: rgb(255, 255, 255); line-height: 30px;">，</span><span style="text-indent: 25px; background-color: rgb(255, 255, 255); line-height: 30px; font-family: &#39;Times New Roman&#39;;">Director of&nbsp;<a name="OLE_LINK21"></a>SKLEST. He assumes vice chief editor of Journal of Explosion and Shock Waves, standing editor of Journal of Acta Ordnance, member of explosion Mechanics professional committee of China Mechanics Association, syndic of China Aerodynamics Association. He has been engaged in research on impact dynamics. His research direction is hypervelocity impact mechanism. He has published 2 monographs, 2 translations of works, 10 SCI and 26 EI papers and won&nbsp;1 a&nbsp;first prize, a second prize and a third prize award of ministerial-level, 1 authorized patent and 5 declared patents.</span></span></p>', 5),
(18, 'Liu-JiPing', '', '<p><span style="font-size: 18px;"><span style="line-height: 24px; background-color: rgb(255, 255, 255); font-family: &#39;Times New Roman&#39;;">Prof</span><span style="font-family: 宋体; line-height: 24px; background-color: rgb(255, 255, 255);">，</span><span style="line-height: 24px; background-color: rgb(255, 255, 255); font-family: &#39;Times New Roman&#39;;">PhD supervisors. He won the “HeLiang-HeLi Science and Technology advancement award” in 2005, successively won 2 second prizes in National Invention Awards, 2 first prizes in&nbsp;<a name="OLE_LINK27"></a>ministerial-level&nbsp;Advanced Technology Award, 4 ministry-class great contribution awards and 5 other science and technology achievement awards. He has published 16 patents, more than 260 papers and 7 monographs.</span></span></p>', 6),
(26, 'Liu-JiPing', '', '<p><span style="font-size: 18px;"><span style="line-height: 24px; background-color: rgb(255, 255, 255); font-family: &#39;Times New Roman&#39;;">Prof</span><span style="font-family: 宋体; line-height: 24px; background-color: rgb(255, 255, 255);">，</span><span style="line-height: 24px; background-color: rgb(255, 255, 255); font-family: &#39;Times New Roman&#39;;">PhD supervisors. He won the “HeLiang-HeLi Science and Technology advancement award” in 2005, successively won 2 second prizes in National Invention Awards, 2 first prizes in&nbsp;<a name="OLE_LINK27"></a>ministerial-level&nbsp;Advanced Technology Award, 4 ministry-class great contribution awards and 5 other science and technology achievement awards. He has published 16 patents, more than 260 papers and 7 monographs.</span></span></p>', 14),
(27, 'Li-QianShu', '', '<p><span style="font-size: 18px;"><span style="font-family: &#39;Times New Roman&#39;; line-height: 24px; background-color: rgb(255, 255, 255);">Prof</span><span style="line-height: 24px; background-color: rgb(255, 255, 255); font-family: 宋体;">，</span><span style="font-family: &#39;Times New Roman&#39;; line-height: 24px; background-color: rgb(255, 255, 255);">PhD supervisors, Doctor got in JiLin University at 1987. He successively assumes the eighth editor member of China Science, vice-chief editor of Journal of Molecule Science of Chinese Chemistry Association, Chinese vice-representative of World Theoretical Organic Chemists Association. He has written 6 monographs collaborated with others and published SCI paper more than 300, a second prize in State Natural Science Award and 3 ministerial-level awards.</span></span></p>', 15),
(28, 'Jiao-Qingjie', '', '<p>&nbsp;<br/></p>', 16);

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
